# Generated by Django 5.2.5 on 2025-08-24 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_betrecord_bet_amount_alter_betrecord_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyThreeRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=16, unique=True, verbose_name='期号')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('betting', '投注中'), ('drawing', '开奖中'), ('closed', '已结束')], default='betting', max_length=16, verbose_name='状态')),
                ('dice1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='骰子1')),
                ('dice2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='骰子2')),
                ('dice3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='骰子3')),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='总点数')),
                ('result_text', models.CharField(blank=True, default='', max_length=16, verbose_name='结果文本')),
                ('settled', models.BooleanField(default=False, verbose_name='已结算')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '幸运快三期',
                'verbose_name_plural': '幸运快三期',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LuckyThreeBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('big', '大'), ('small', '小'), ('odd', '单'), ('even', '双')], max_length=16, verbose_name='投注类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('odds', models.DecimalField(decimal_places=2, default=1.95, max_digits=5, verbose_name='赔率')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('won', '已中奖'), ('lost', '未中奖'), ('settled', '已结算')], default='pending', max_length=16, verbose_name='状态')),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='派奖金额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_three_bets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bets.luckythreeround', verbose_name='期号')),
            ],
            options={
                'verbose_name': '幸运快三投注',
                'verbose_name_plural': '幸运快三投注',
                'indexes': [models.Index(fields=['round', 'user'], name='bets_luckyt_round_i_51bfb0_idx')],
            },
        ),
    ]
