# Generated by Django 5.2.5 on 2025-08-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_luckythreeround_luckythreebet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luckythreeround',
            options={'ordering': ['-created_at'], 'verbose_name': '幸运快三结果', 'verbose_name_plural': '幸运快三结果'},
        ),
        migrations.RemoveField(
            model_name='luckythreeround',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='luckythreeround',
            name='result_text',
        ),
        migrations.RemoveField(
            model_name='luckythreeround',
            name='settled',
        ),
        migrations.RemoveField(
            model_name='luckythreeround',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='luckythreeround',
            name='status',
        ),
        migrations.AlterField(
            model_name='luckythreeround',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterModelTable(
            name='luckythreeround',
            table='result_luckythreeround',
        ),
        migrations.DeleteModel(
            name='LuckyThreeBet',
        ),
    ]
